name: Save and Extract Data 04

on:
  schedule:
    - cron: '30 8 * * *'  # 19:30 UTC (which is 20:30 GMT+1)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python scrape_and_save_04.py
      env:
        MONGO_URL: ${{ secrets.MONGO_URI }}
        GITHUB_TOKEN: ${{ secrets.GETHUB_TOKEN }}